shutdown_timeout: 5s

targets:

- path: ./test/test1
  include_regexp:
    - .*.go$
    - .*.env$
  exclude_regexp:
    - .*bibaboba.*
  commands:
    - pwd
    - python3 ../err_writer.py
  log_file: biba.log

- path: /home/gingersamurai/coding/projects/gobserver/test/test2
  include_regexp:
    - .*.py$
    - .*GOODBIBA.*
  exclude_regexp:
    - .*BADBIBA.*
  commands:
    - sleep 3