# таймаут для завершения работы
shutdown_timeout: 5s

# конфигурация целей для отслеживания
targets:

- path: ./test/test1
  include_regexp:
    - .*.go$
    - .*.env$
  exclude_regexp:
    - .*bad.*
  commands:
    - pwd
    - python3 ../err_writer.py
    - ls
  log_file: log1.txt

- path: /home/gingersamurai/coding/projects/gobserver/test/test2
  include_regexp:
    - .*.py$
  exclude_regexp:
    - .*\.txt$
  commands:
    - sleep 3